// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDFooSncU4SswtgKUdLUKi98ksV21IZ7E',
    appId: '1:99956857410:web:ca8e506322ba21e298abdb',
    messagingSenderId: '99956857410',
    projectId: 'exploreease-651dc',
    authDomain: 'exploreease-651dc.firebaseapp.com',
    storageBucket: 'exploreease-651dc.appspot.com',
    measurementId: 'G-CF896BB9FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1zqFksDnLzGeZFefwaT9pZI_Bt7MndLk',
    appId: '1:99956857410:android:0c27fb01281983e598abdb',
    messagingSenderId: '99956857410',
    projectId: 'exploreease-651dc',
    storageBucket: 'exploreease-651dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ6TjGp_x_Uj9UsBc4PceR3VIJjFaWfm8',
    appId: '1:99956857410:ios:069362808bec009d98abdb',
    messagingSenderId: '99956857410',
    projectId: 'exploreease-651dc',
    storageBucket: 'exploreease-651dc.appspot.com',
    iosBundleId: 'com.example.exploreease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ6TjGp_x_Uj9UsBc4PceR3VIJjFaWfm8',
    appId: '1:99956857410:ios:069362808bec009d98abdb',
    messagingSenderId: '99956857410',
    projectId: 'exploreease-651dc',
    storageBucket: 'exploreease-651dc.appspot.com',
    iosBundleId: 'com.example.exploreease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDFooSncU4SswtgKUdLUKi98ksV21IZ7E',
    appId: '1:99956857410:web:77e93c4448435cdd98abdb',
    messagingSenderId: '99956857410',
    projectId: 'exploreease-651dc',
    authDomain: 'exploreease-651dc.firebaseapp.com',
    storageBucket: 'exploreease-651dc.appspot.com',
    measurementId: 'G-4KJB1NQFG9',
  );
}
